# -*- coding: utf-8 -*-
"""Brain Tumor Segmentation using U-Net on MRI Images

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHJgBZ28_NlJ4COyKx1khTP9S_hujTbj
"""

from google.colab import drive
drive.mount('/content/drive')

"""#**Required Libraries**"""

!pip install tensorflow opencv-python matplotlib scikit-learn streamlit

"""#**Libraries Import**"""

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, models

"""#**Set the Dataset Path**"""

image_path = '/content/drive/MyDrive/brain_tumor/images'
mask_path = '/content/drive/MyDrive/brain_tumor/masks'

"""#**Load Images + process**"""

IMG_SIZE = 128

images = []
masks = []

image_files = sorted(os.listdir(image_path))
mask_files = sorted(os.listdir(mask_path))

for i in tqdm(range(min(len(image_files), len(mask_files)))):
    img = cv2.imread(os.path.join(image_path, image_files[i]))
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0

    mask = cv2.imread(os.path.join(mask_path, mask_files[i]), 0)
    mask = cv2.resize(mask, (IMG_SIZE, IMG_SIZE))
    mask = mask / 255.0
    mask = np.expand_dims(mask, axis=-1)

    images.append(img)
    masks.append(mask)

images = np.array(images, dtype=np.float32)
masks = np.array(masks, dtype=np.float32)

print(images.shape, masks.shape)

"""#**Train/Test split**"""

X_train, X_test, y_train, y_test = train_test_split(
    images, masks, test_size=0.15, random_state=42
)

"""#**Metrics**"""

def dice_coef(y_true, y_pred):
    y_true_f = tf.keras.backend.flatten(y_true)
    y_pred_f = tf.keras.backend.flatten(y_pred)
    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return (2. * intersection + 1) / (tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + 1)

def dice_loss(y_true, y_pred):
    return 1 - dice_coef(y_true, y_pred)

"""#**U-Net Model**"""

def unet_model(input_size=(128,128,3)):
    inputs = layers.Input(input_size)

    c1 = layers.Conv2D(64, 3, activation='relu', padding='same')(inputs)
    c1 = layers.Conv2D(64, 3, activation='relu', padding='same')(c1)
    p1 = layers.MaxPooling2D()(c1)

    c2 = layers.Conv2D(128, 3, activation='relu', padding='same')(p1)
    c2 = layers.Conv2D(128, 3, activation='relu', padding='same')(c2)
    p2 = layers.MaxPooling2D()(c2)

    c3 = layers.Conv2D(256, 3, activation='relu', padding='same')(p2)
    c3 = layers.Conv2D(256, 3, activation='relu', padding='same')(c3)
    c3 = layers.Dropout(0.3)(c3)

    u1 = layers.UpSampling2D()(c3)
    u1 = layers.concatenate([u1, c2])
    c4 = layers.Conv2D(128, 3, activation='relu', padding='same')(u1)

    u2 = layers.UpSampling2D()(c4)
    u2 = layers.concatenate([u2, c1])
    c5 = layers.Conv2D(64, 3, activation='relu', padding='same')(u2)

    outputs = layers.Conv2D(1, 1, activation='sigmoid')(c5)

    return models.Model(inputs, outputs)

"""#**Compile (accuracy Remove)**"""

model = unet_model()

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss=dice_loss,
    metrics=[dice_coef]
)

model.summary()

"""#**Train Model**"""

callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True),
    tf.keras.callbacks.ModelCheckpoint("best_model.h5", save_best_only=True)
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=8,
    callbacks=callbacks
)

"""#**Predict test**"""

pred = model.predict(X_test)

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.title("MRI")
plt.imshow(X_test[0])

plt.subplot(1,3,2)
plt.title("Actual")
plt.imshow(y_test[0].squeeze(), cmap='gray')

plt.subplot(1,3,3)
plt.title("Predicted")
plt.imshow(pred[0].squeeze() > 0.3, cmap='gray')

plt.show()

"""#**Save model**"""

model.save("model.h5")